Repository GDSCJUET/DSC_Guna_Website, pull requests merged in 2022-10, with the labels that each got.

#22 [Doc] Added Contributing Guidelines
  CONTRIBUTING.md
  README.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#24 [Fix] Redundant StyleSheets
  CSS/index.css
  CSS/teams.css
  CSS/utilities.css
  README.md
  index.html
  pages/teams.html
Labels: hacktoberfest, hacktoberfest-accepted

#25 [fix] Fixed Blog page to 404
  CSS/blogs.css
  pages/blogs.html
  src/blog.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#28 [FIX] Fixed position for Menu icon
  CSS/index.css
  CSS/teams.css
Labels: hacktoberfest, hacktoberfest-accepted

#27 [feat] Added Events Page
  .gitignore
  CSS/events.css
  index.html
  pages/events.html
  pages/teams.html
Labels: hacktoberfest, hacktoberfest-accepted

#29 [FIX]Arranges Redundant CSS
  CSS/index.css
  CSS/main.css
  CSS/teams.css
  index.html
  pages/blogs.html
  pages/events.html
  pages/teams.html
Labels: hacktoberfest-accepted

#32 Changed Color for Contact us icons
  assets/icons/discord.svg
  assets/icons/github.svg
  assets/icons/instagram.svg
  assets/icons/linkedin.svg
  assets/icons/twitter.svg
Labels: hacktoberfest, hacktoberfest-accepted
